// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class Attachment;
@class AttachmentBuilder;
@class Header;
@class HeaderBuilder;



@interface HeaderRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define Attachment_key @"key"
#define Attachment_value @"value"
@interface Attachment : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasKey_:1;
  BOOL hasValue_:1;
  NSString* key;
  NSData* value;
}
- (BOOL) hasKey;
- (BOOL) hasValue;
@property (readonly, strong) NSString* key;
@property (readonly, strong) NSData* value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AttachmentBuilder*) builder;
+ (AttachmentBuilder*) builder;
+ (AttachmentBuilder*) builderWithPrototype:(Attachment*) prototype;
- (AttachmentBuilder*) toBuilder;

+ (Attachment*) parseFromData:(NSData*) data;
+ (Attachment*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Attachment*) parseFromInputStream:(NSInputStream*) input;
+ (Attachment*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Attachment*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Attachment*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AttachmentBuilder : PBGeneratedMessageBuilder {
@private
  Attachment* resultAttachment;
}

- (Attachment*) defaultInstance;

- (AttachmentBuilder*) clear;
- (AttachmentBuilder*) clone;

- (Attachment*) build;
- (Attachment*) buildPartial;

- (AttachmentBuilder*) mergeFrom:(Attachment*) other;
- (AttachmentBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AttachmentBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasKey;
- (NSString*) key;
- (AttachmentBuilder*) setKey:(NSString*) value;
- (AttachmentBuilder*) clearKey;

- (BOOL) hasValue;
- (NSData*) value;
- (AttachmentBuilder*) setValue:(NSData*) value;
- (AttachmentBuilder*) clearValue;
@end

#define Header_crcCode @"crcCode"
#define Header_messageId @"messageId"
#define Header_type @"type"
#define Header_priority @"priority"
#define Header_from @"pb_from"
#define Header_to @"to"
#define Header_groupId @"groupId"
#define Header_password @"password"
#define Header_socketType @"socketType"
#define Header_attachment @"attachment"
@interface Header : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasFrom_:1;
  BOOL hasTo_:1;
  BOOL hasPassword_:1;
  BOOL hasType_:1;
  BOOL hasPriority_:1;
  BOOL hasCrcCode_:1;
  BOOL hasSocketType_:1;
  BOOL hasMessageId_:1;
  BOOL hasGroupId_:1;
  NSString* pb_from;
  NSString* to;
  NSString* password;
  NSData* type;
  NSData* priority;
  SInt32 crcCode;
  SInt32 socketType;
  SInt64 messageId;
  SInt64 groupId;
  NSMutableArray * attachmentArray;
}
- (BOOL) hasCrcCode;
- (BOOL) hasMessageId;
- (BOOL) hasType;
- (BOOL) hasPriority;
- (BOOL) hasFrom;
- (BOOL) hasTo;
- (BOOL) hasGroupId;
- (BOOL) hasPassword;
- (BOOL) hasSocketType;
@property (readonly) SInt32 crcCode;
@property (readonly) SInt64 messageId;
@property (readonly, strong) NSData* type;
@property (readonly, strong) NSData* priority;
@property (readonly, strong) NSString* pb_from;
@property (readonly, strong) NSString* to;
@property (readonly) SInt64 groupId;
@property (readonly, strong) NSString* password;
@property (readonly) SInt32 socketType;
@property (readonly, strong) NSArray * attachment;
- (Attachment*)attachmentAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HeaderBuilder*) builder;
+ (HeaderBuilder*) builder;
+ (HeaderBuilder*) builderWithPrototype:(Header*) prototype;
- (HeaderBuilder*) toBuilder;

+ (Header*) parseFromData:(NSData*) data;
+ (Header*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Header*) parseFromInputStream:(NSInputStream*) input;
+ (Header*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Header*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Header*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HeaderBuilder : PBGeneratedMessageBuilder {
@private
  Header* resultHeader;
}

- (Header*) defaultInstance;

- (HeaderBuilder*) clear;
- (HeaderBuilder*) clone;

- (Header*) build;
- (Header*) buildPartial;

- (HeaderBuilder*) mergeFrom:(Header*) other;
- (HeaderBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HeaderBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCrcCode;
- (SInt32) crcCode;
- (HeaderBuilder*) setCrcCode:(SInt32) value;
- (HeaderBuilder*) clearCrcCode;

- (BOOL) hasMessageId;
- (SInt64) messageId;
- (HeaderBuilder*) setMessageId:(SInt64) value;
- (HeaderBuilder*) clearMessageId;

- (BOOL) hasType;
- (NSData*) type;
- (HeaderBuilder*) setType:(NSData*) value;
- (HeaderBuilder*) clearType;

- (BOOL) hasPriority;
- (NSData*) priority;
- (HeaderBuilder*) setPriority:(NSData*) value;
- (HeaderBuilder*) clearPriority;

- (BOOL) hasFrom;
- (NSString*) pb_from;
- (HeaderBuilder*) setFrom:(NSString*) value;
- (HeaderBuilder*) clearFrom;

- (BOOL) hasTo;
- (NSString*) to;
- (HeaderBuilder*) setTo:(NSString*) value;
- (HeaderBuilder*) clearTo;

- (BOOL) hasGroupId;
- (SInt64) groupId;
- (HeaderBuilder*) setGroupId:(SInt64) value;
- (HeaderBuilder*) clearGroupId;

- (BOOL) hasPassword;
- (NSString*) password;
- (HeaderBuilder*) setPassword:(NSString*) value;
- (HeaderBuilder*) clearPassword;

- (BOOL) hasSocketType;
- (SInt32) socketType;
- (HeaderBuilder*) setSocketType:(SInt32) value;
- (HeaderBuilder*) clearSocketType;

- (NSMutableArray *)attachment;
- (Attachment*)attachmentAtIndex:(NSUInteger)index;
- (HeaderBuilder *)addAttachment:(Attachment*)value;
- (HeaderBuilder *)setAttachmentArray:(NSArray *)array;
- (HeaderBuilder *)clearAttachment;
@end


// @@protoc_insertion_point(global_scope)
